//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUShopNearby
{
    using System;
    using System.Collections.Generic;
    
    public partial class Propietario
    {
        public int idPropietario { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Cedula { get; set; }
        public string N_Telefono { get; set; }
        public string Usuario { get; set; }
        public string Contrasena { get; set; }
    }
}
