//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUShopNearby
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tienda
    {
        public int idTienda { get; set; }
        public string Nombre { get; set; }
        public string R_Social { get; set; }
        public string N_Telefono { get; set; }
        public string Direccion { get; set; }
        public string Estado { get; set; }
        public string Horario { get; set; }
        public Nullable<int> idProvincia { get; set; }
        public Nullable<int> idCiudad { get; set; }
        public Nullable<int> idSector { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
        public virtual Provincia Provincia { get; set; }
        public virtual Sector Sector { get; set; }
    }
}
